### ISSUE TITLE
`Ctrl+A` doesn't work in "Sign in" pop-up

### ISSUE THREAD

**Issue by AlexWayfer** [atom/teletype#208]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

`Ctrl+A` doesn't work in "Sign in" pop-up.

### Steps to Reproduce

1. Open "Sign in" pop-up
2. Enter some text into field
3. Press `Ctrl+A`

**Expected behavior:**

All text is selected.

**Actual behavior:**

Nothing.

**Reproduces how often:**

100%

### Versions

```
$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.15.0
```

### Additional Information

![image](https://user-images.githubusercontent.com/6510020/32879659-ea3b7072-cabb-11e7-90a7-d494a8d9218f.png)

**Comment by as-cii** [comment]
Hello @AlexWayfer, and thanks for your report! 🙇 I think this is an issue in Atom core, and I have provided a pull-request to fix it (I also mentioned you on it in case you're interested).

Since it would change the behavior for all Windows and Linux users and considering the impact of this issue on the teletype package is not major, I would like those changes to go through a full release cycle (i.e. bake on master for a while, then release them to beta, and then finally to stable).

**Comment by AlexWayfer** [comment]
Hello, @as-cii! Thank you! You're very cool!

I'll close this issue (cause it's not Teletype issue) and will follow that PR (and everyone with this problem, who will find this issue, can do this too).
