### ISSUE TITLE
Would Like to contribute to this Package

### ISSUE THREAD

**Issue by pavitran** [atom/teletype#209]
I'd like to contribute to this repo, but don't know where to start. Can anyone guide me in the right direction

**Comment by happycollision** [comment]
Have a look at the Contributing guide in this repo. (It redirects to the Atom one, but better to start at the source here, if they ever make addendums.)

[Contributing](https://github.com/atom/teletype/blob/master/CONTRIBUTING.md)

**Comment by jasonrudolph** [comment]
> I'd like to contribute to this repo, but don't know where to start.

:wave: Hi, @pavitran! Welcome! I can offer a few resources to hopefully help you get started:

- [`CONTRIBUTING.md`](https://github.com/atom/teletype/blob/master/CONTRIBUTING.md) is the best place to start. It's a long read, but it's an important resource for learning how to effectively contribute.
- Once you're familiar with that info, [open issues](https://github.com/atom/teletype/issues) are a great place to find areas where contributions would be helpful, especially issues with the [`bug`](https://github.com/atom/teletype/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [`help wanted`](https://github.com/atom/teletype/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) labels.
- If you're interested in taking on particularly *large* effort, I recommend first opening an issue to describe the proposed change, the motivation behind the change, and the tradeoffs associated with the change. Think of it as [RFC](https://en.wikipedia.org/wiki/Request_for_Comments), in which your asking for the team's feedback before you invest significant time into implementation. https://github.com/atom/teletype/issues/100 is a good example.

I hope this helps. Because we treat our issues list as our backlog, I'm going to close this issue, but feel free to reply with any follow-up questions, and I'll try to help.
