### ISSUE TITLE
Sublime Text version? 😉

### ISSUE THREAD

**Issue by marsjaninzmarsa** [atom/teletype#223]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

Cross-editor collaboration - that would be something, and AFAIK there are no technical reasons against making Teletype cross-compliant protocol. My vote is to begin with Sublime. 😉

**Comment by jasonrudolph** [comment]
> AFAIK there are no technical reasons against making Teletype cross-compliant protocol.

Indeed! As described in the [blog post announcing Teletype for Atom](https://blog.atom.io/2017/11/15/code-together-in-real-time-with-teletype-for-atom.html#editor-agnostic-client-library):

>> **Editor-agnostic client library**: The Teletype Atom package implements UI components and Atom-specific integration code, but most of the logic lives in an editor-agnostic library called [teletype-client](https://github.com/atom/teletype-client). Our protocols and API may churn for a while as we develop the system, but it should be possible to integrate teletype-client into any web-based application or even package it in an Electron-based server to talk to it from native editors. Supporting inter-operation between different text editors is definitely part of our long term vision.

We'd love to interoperate with other text editors. In the near term, bringing Teletype to more text editors will likely require the help of engineers that are familiar with creating packages for those text editors. Because of this, and because interoperability with Sublime Text would be a separate project in a separate repository, and because we treat our issues list as [our backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), I'm going to close this issue to keep the _Atom for Teletype_ backlog clean and focused. 😅
