### ISSUE TITLE
How to see proyect files of my friend?

### ISSUE THREAD

**Issue by DenzelCode** [atom/teletype#225]
Im using Teletype with a friend, but, i can't see his files :(

**Comment by jasonrudolph** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
