### ISSUE TITLE
Attribute commit to everybody who has edited at least one file in that commit

### ISSUE THREAD

**Issue by Dmendoza99** [atom/teletype#305]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description
my friend didnt have any credits in the lines scheme on the repo

### Steps to Reproduce
1.work on pair
2.both push on the same repo
3. done the guest doesn't have credits

**Expected behavior:**
every user get the line they did on the new version of the code

**Actual behavior:**
the server gets all the lines

**Reproduces how often:**
all ways

### Versions
atom : 1.22.0
apm 1.18.8
### Additional Information
Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

**Comment by as-cii** [comment]
Hello @Dmendoza99, and thanks for opening this!

If I understand correctly, the expected behavior would be to have line-by-line commit attribution on Git after working with other people on a set of files via Teletype. If that's the case, I think that would be extremely valuable, and it would be interesting to go even further by storing authors on a per-character basis. Unfortunately, as of today, Git allows to store authors only on a per-commit basis, so we would have to attribute the entire commit to everybody who has made at least one edit since the last commit. Even if that's more coarse grained, I think it would still provide a ton of value and it's something we've been thinking about too.

As we prioritize future work, we'll be looking at feature requests like this one to determine where we can deliver the most benefit with the available engineering resources (i.e., full-time Atom engineers, community maintainers, and new contributors). In the meantime, if this feature would benefit your workflow on a regular basis, adding a 👍 emoji reaction to the issue body is a great way to let us know.

**Comment by BrianHung** [comment]
This is noted in [1], but is Git - an asynchronous version control system - suitable for synchronous, real-time collaboration?

[1] https://github.com/atom-archive/xray/tree/master/memo_core
