### ISSUE TITLE
Error occurs when there's no internet

### ISSUE THREAD

**Issue by ungb** [atom/teletype#313]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

Error occurs when there's no internet
### Steps to Reproduce

1. Install Atom and Teletype on atom and close atom
1. turn off your wifi/internet
1. Open atom

**Expected behavior:**

[What did you expect to happen?]
no error pops up.
**Actual behavior:**

[What actually happened instead?]
the following error occurs
![image](https://user-images.githubusercontent.com/5624870/35593443-2803388a-05cd-11e8-9fa0-bc41097403b7.png)

**Reproduces how often:**

[What percentage of the time does this happen?]
100%

### Versions
1.23.3 Atom
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by jasonrudolph** [comment]
This issue is addressed in #309 and those improvements will be included in the next Teletype release.

With those changes in place, if you open Atom when your internet connection is down, Teletype will inform you about the error and instruct you to "Make sure your internet connection is working and restart the package." See screenshots in https://github.com/atom/teletype/pull/309#issuecomment-359516449.
