### ISSUE TITLE
Question on Functionality: Closing and Opening Portals

### ISSUE THREAD

**Issue by sguthals** [atom/teletype#359]
👋 
I have a question regarding expected functionality. 

I have a project folder opened in Atom. I then:
1. Opened a file
2. Opened a portal
3. Folks joined

Then I wanted to close that and get ready for my next session, so I:
1. Closed the portal (stopped sharing)
2. Closed that file
3. Opened another file
4. Started sharing again

When I did this
> 4. Started sharing again

I noticed that the person that joined the first time were still able to access the new file I had opened. 
<img width="338" alt="screen shot 2018-04-09 at 9 17 13 am" src="https://user-images.githubusercontent.com/1314285/38509472-cf578af2-3bd6-11e8-8953-62c4be2384d1.png">

It seems that the URLs were the same for both times:
atom://teletype/portal/f0e1e689-71b8-4448-9287-d80d99653130

*And* new folks are not able to join. 

Maybe the portal was "closed" but not all the way? I'm not sure. 

I closed Atom and restarted it and was able to properly open a new portal. 

So maybe this is a bug after all. 

Atom: 1.22.1
Teletype: 0.12.0

I also received [this error](https://github.com/atom/teletype/issues/357#issuecomment-379807660) in the initial sharing session.

**Comment by jasonrudolph** [comment]
> I have a question regarding expected functionality.

I think your expectations are correct. Closing a portal _should_ cease all sharing. 😅 All of your steps were reasonable steps to obtain the desired effects, so thanks for letting us know that you ran into this incorrect behavior.

> I also received [this error](https://github.com/atom/teletype/issues/357#issuecomment-379807660) in the initial sharing session.

Gotcha. We're tracking that issue in https://github.com/atom/teletype/issues/360.

> And new folks are not able to join.
> 
> Maybe the portal was "closed" but not all the way? I'm not sure.
> 
> I closed Atom and restarted it and was able to properly open a new portal.

Given that you experienced that error while collaborating in the first portal, I suspect the error likely prevented the portal from being closed, and prevented the new one from opening properly. Because of that I'm going to close this issue. (I'm pretty sure #360 is the real culprit.) If you experience this behavior in the absence of the issue you observed in #360, please let us know, and I'll re-open this issue.
