### ISSUE TITLE
i cant install teletype. It kept giving errors and when i finally got to the install button i tried to click it but teletype still wouldn't install.

### ISSUE THREAD

**Issue by Onnoman** [atom/teletype#361]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

[What did you expect to happen?]

**Actual behavior:**

[What actually happened instead?]

**Reproduces how often:**

[What percentage of the time does this happen?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Specifically we need to know what errors you were seeing and if you tried any of the steps in the debugging guide http://flight-manual.atom.io/hacking-atom/sections/debugging/. Don't hesitate to reach out with more information and we will be happy to reopen this issue.

Thanks for understanding and meeting us half way :grinning:
