### ISSUE TITLE
Teletype asking for Sign in With Github every time

### ISSUE THREAD

**Issue by X52p** [atom/teletype#412]
### Description

Everytime I restart Atom, Teletype asks me to sign into GitHub again.

### Steps to Reproduce

1. [open Atom]
2. [enter token]
3. (Optional) [work with Teletype]
4. [exit Atom]
5. [start Atom]

**Expected behavior:**

[Teletype should recognize my saved token]

**Actual behavior:**

[I get asked for the token again]

**Reproduces how often:**

[every time]

### Versions
Atom --verions:
Atom    : 1.30.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm --version:
apm  2.1.2
npm  6.4.1
node 10.10.0 x64
atom 1.30.0
python 2.7.15
git 2.19.0

### Additional Information
I'm using Arch Linux
I already tried:
 -reinstalling the package
 -reconnecting Teletype to GitHub by revoking access and granting it again

**Comment by 50Wliu** [comment]
> Atom : 1.30.0
> Electron: 2.0.9

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
