### ISSUE TITLE
Allow use of Teletype without connecting a GitHub account

### ISSUE THREAD

**Issue by SilverWolf32** [atom/teletype#419]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

When I attempted to use Teletype for the first time, it required me to create a GitHub account. This shouldn't be necessary; there's no reason why people should need accounts of any sort in order to use a (mostly) peer-to-peer service. It would be nice if Teletype instead connected and created a portal link without requiring an account first.

Ideally the service would be entirely peer-to-peer, but using a central server for setup is understandable -- however, nowhere is it mentioned that you need an account!
Also see #416.

**Comment by rsese** [comment]
Thanks for the feedback - though requiring authentication with a GitHub account isn't something we're likely to change at this point, we'll go ahead and pass along your thoughts to the maintainers team.  Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.

**Comment by SilverWolf32** [comment]
Thank you.

Would changing the API Server Base URL in the Teletype package settings allow using a self-hosted instance of teletype-server instead of GitHub authentication, or would I have to tweak the code? (It also says it should only be changed for development purposes. What's up with that?)
