### ISSUE TITLE
unsafe eval issue

### ISSUE THREAD

**Issue by NikosEfthias** [atom/teletype#446]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the [debugging guide][debugging-guide]
    * Checked the FAQs on the [message board][message-board] for common solutions
    * Checked that your issue [isn't already filed][already-filed]?

[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/teletype/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. install teletype
2. watch it fail

**Expected behavior:**

Install successfully 
**Actual behavior:**

Gives an error message
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

**Reproduces how often:**

every single time

### Versions

> `atom --version`
```
Atom    : 1.36.0
Electron: 4.1.1
Chrome  : 69.0.3497.128
Node    : 10.11.0
```
> `apm --version`
```
apm  2.1.7
npm  6.9.0
node 11.14.0 x64
atom 1.36.0
python 2.7.16
git 2.21.0
```

### Additional Information

This happens on a fresh install with no config

**Comment by iron-condor** [comment]
I can verify that I'm also having this issue, and the person that I was attempting to collaborate with had the same issue as well.

We are both running 64-bit Arch Linux systems, on the 5.0.7-arch1-1-ARCH kernel

> atom --version

```
Atom    : 1.36.0
Electron: 4.1.4
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

> apm --version

```

apm  2.1.7
npm  6.9.0
node 11.14.0 x64
atom 1.36.0
python 2.7.16
git 2.21.0

```

**Comment by rsese** [comment]
Thanks for the report!

> Atom    : 1.36.0
> Electron: 4.1.4

Based on this version information, we can see that you're currently using an unofficial build or distribution of Atom (i.e. the current release version of Atom, 1.3.0, is on Electron 2.0.18).   Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by ioquatix** [comment]
**Atom**: 1.36.1 x64
**Electron**: 4.1.4
**OS**: "Arch Linux"
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.3


### Stack Trace

Failed to activate the teletype package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (<anonymous>)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client_pb.js:12:14)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client_pb.js:5561:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/router.js:2:25)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/router.js:135:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:3:16)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:731:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client.js:5:16)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client.js:197:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-dark-ui-slim 0.47.1 
atom-soda-dark-ui 1.1.0 
atom-solo-dark-ui 1.3.0 
autoclose-html 0.23.0 
color-picker 2.3.0 
editor-stats 0.17.0 
escape-utils 0.5.3 
file-icons 2.1.32 
git-blame 1.8.0 
git-plus 8.6.3 
imdone-atom 2.4.31 
imdone-atom-github 0.1.11 
language-latex 1.2.0 
language-openscad 0.4.3 
language-svg 0.9.2 
language-trenni 0.2.1 
latex 0.50.2 
markdown-preview-plus 3.8.1 
multi-cursor 2.1.5 
paraiso-dark 2.0.2 
pdf-view 0.71.0 
rspec 0.4.0 
script-runner 2.3.1 
solarized-dark-ui 0.3.2 
solarized-light-ui 0.1.0 
svg-preview 0.14.0 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
teletype 0.13.3 
travis-ci-status 1.3.1 
unity-dark-ui 2.0.9 
```

**Comment by 50Wliu** [comment]
> **Electron**: 4.1.4

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by 50Wliu** [comment]
As this issue is happening exclusively with unofficial distributions, I'm locking this.
