### ISSUE TITLE
Attempting to join portal failed with error: Connecting to peer timed out

### ISSUE THREAD

**Issue by Rijul5** [atom/teletype#472]
I am trying to use teletype-client library in vs-code. The objective of this task is to share/join portal with vs code and atom editor. I am using the latest version of teletype-client library in vs code project.

Issue: While launching a portal from Atom editor on my system and using its portal ID in order to join the portal from vs code, I am getting the below error:
Failed to join portal: Attempting to join portal 5ebb2a6e-2508-4769-bd3e-9fc37e4114d2 failed with error: Connecting to peer timed out

Replication Steps: VS Code extension written in typescript for teletype. I have used the teletype-client library in order to join the portal launched from atom editor.

Logs:
In Atom, after opening the DevTools , I enabled Pusher logging by running the following in the DevTools Console:
```
atom.packages.getLoadedPackage('teletype').mainModule.client.pubSubGateway.pusherClient.constructor.logToConsole = true
```
and shared the portal. I get the below output:
![image](https://user-images.githubusercontent.com/32622151/63219639-2a1d2200-c144-11e9-90c0-940ee19b307c.png)

* In vs-code, I get the below error:
Failed to join portal: Attempting to join portal 5ebb2a6e-2508-4769-bd3e-9fc37e4114d2 failed with error: Connecting to peer timed out.
The error is most likely because the state of peer-connection object is not changing to "connected". It remains in "connecting" state as shown below:

![image](https://user-images.githubusercontent.com/32622151/63219674-ea0a6f00-c144-11e9-8453-81a55ed4f038.png)

Also, I am using the pusher-js version in vs code (const Pusher = require('pusher-js')) and not (const Pusher = require('pusher-js/dist/web/pusher')) as provided in the latest version of teletype-client [here](https://github.com/atom/teletype-client/pull/38/files) because otherwise I am getting the below error:

![image](https://user-images.githubusercontent.com/32622151/63219652-4de06800-c144-11e9-9d98-3d7269c21b18.png)

I have also tried the version as mentioned [here](https://github.com/nonameentername/teletype-client/commit/3332ab160f19dde12a327a69aa3756a2a9f3d288). I tried both cases "pusher" and "socketcluster" but i get the same error - Failed to join portal: Attempting to join portal 5ebb2a6e-2508-4769-bd3e-9fc37e4114d2 failed with error: Connecting to peer timed out.

Please advice on this.

**Comment by rsese** [comment]
Thanks for reaching out and for the detailed report -

> The objective of this task is to share/join portal with vs code and atom editor. I am using the latest version of teletype-client library in vs code project.

While this definitely sounds neat that you're trying to connect to the same portal from Atom and VS Code, with the team's current priorities, investigating Teletype's use outside of Atom isn't something the maintainers will be able to help investigate right now unfortunately.

The best resource I can share is the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638) - there are number of helpful community members there that might be able to help or who might be interested in the same use case.

Since this isn't something the team would investigate or work on, I'm going to close this issue but thanks again for your interest and I do hope you get this up and running!
