### ISSUE TITLE
relogin

### ISSUE THREAD

**Issue by hanbing5201** [atom/teletype#473]
# relogin
How do I relogin with  account B after I loged with account A

**Comment by rsese** [comment]
Thanks for reaching out!

From the command palette (<kbd>Cmd+Shift+P</kbd> on macOS for example), run `Teletype: Sign Out`.  You can then get a token for account B and use that to sign in with the other account.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
