### ISSUE TITLE
W5G-Atom

### ISSUE THREAD

**Issue by W5G** [atom/teletype#526]

**Comment by W5G** [comment]
W5G Azure Github adım adım ATOM'a

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
