### ISSUE TITLE
Package Initialization Error

### ISSUE THREAD

**Issue by arjunvtsuresh** [atom/teletype#548]
### Diagnostics

```
Request: GET https://opensoftware.xyz/protocol-version
Status Code: 404
Body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.38 (Raspbian) Server at opensoftware.xyz Port 443</address>
</body></html>


```
### Versions

**Teletype version**: v0.13.4
**Atom version**: 1.48.0
**Platform**: win32

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
